### ISSUE TITLE
The game crashes when i put the lantern in the slot

### ISSUE THREAD

**Issue by AVeryLittleGhost** [txnimc/ImmersiveLanterns#11]
![Captura](https://github.com/user-attachments/assets/9c642e58-366d-4b4c-8ea2-e039f2516120)
[crash-2024-10-18_16.07.59-client.txt](https://github.com/user-attachments/files/17441551/crash-2024-10-18_16.07.59-client.txt)

**Comment by nthxny** [comment]
Your Sodium is out of date.
