### ISSUE TITLE
Curios Support (Feature Request)

### ISSUE THREAD

**Issue by ZzamZ** [txnimc/ImmersiveLanterns#2]
Any shot you could make this work with curios/adorned (the curios fork for 1.21+)? Would absolutely love if you could! If not totally understand just figured id mention it!

**Comment by nthxny** [comment]
Adorned is NeoForge only and simply just the old Curios mod on a newer version. Accessories has cross platform support on multiple modloaders, is being actively updated, and has a shared API on 1.20 and 1.21. 

You should switch to Accessories, and install the Curios Compat Layer. It should be a drop-in replacement.
