### ISSUE TITLE
How is it ended up here?

### ISSUE THREAD

**Issue by Niconoko** [txnimc/ImmersiveLanterns#3]
![image](https://github.com/user-attachments/assets/a30f785a-5042-4045-b4dc-aaa9ce6b2ea5)
Doesn't seem to compatible with https://modrinth.com/resourcepack/tras-fresh-player, it went up on me face instead (´・ω・｀)

PS. There was a crash before but it seem to fixed itself or not sure what config me did to fix it.

**Comment by nthxny** [comment]
You using the latest versions of the mod and Accessories? This should be fixed already.

**Comment by Niconoko** [comment]
Ah.. there it is, guess that's why me still using old version of that.
Here's the crashlog - https://pastebin.com/NGNtFSeH

**Comment by nthxny** [comment]
Yeah this should all be resolved now, if you're still crashing on latest versions of Accessories and Immersive Lanterns, lmk
