### ISSUE TITLE
Item visually doesnt show up

### ISSUE THREAD

**Issue by Sk1nny18** [txnimc/ImmersiveLanterns#4]
![2024-10-13_12 58 22](https://github.com/user-attachments/assets/5053e75f-1a57-47ac-b7d4-0534eb29a670)
![2024-10-13_12 58 51](https://github.com/user-attachments/assets/ac339111-dd3a-46f2-8ea5-3e10c1b79779)

For some reason the item doesnt visually show up,

I have the latest version of all support mods, ive tried using trinkets Compat layer, and it doesnt seem to be a problem with my player animation mods or my YDM weapons 

I can equip and the items lighting does show up

**Comment by nthxny** [comment]
can you link your log files and modlist?
