### ISSUE TITLE
no mob drops

### ISSUE THREAD

**Issue by bonedaddy6969** [txnimc/ImmersiveLanterns#5]
i have the mod set up and working. on the belt and emitting light. but there are no mob drops with the mod active. ive check to make sure domobdrops was set to true and when i turn the mod off the mobs drop loot again. so not sure whats going on. being on 1.21.1 running  through fabric on curseforge. there are no other mods that i can get to work with the right versions so this is the only mod i can find to have hands free dynamic light. any idea?

**Comment by nthxny** [comment]
Link your latest log file

**Comment by nthxny** [comment]
This mod has nothing to do with mobs, mob drops, or looting in general. I just booted up 1.21.1 Fabric with latest versions of this and Accessories and have no issues.

I don't see how this could possibly be caused by this mod but you are welcome to link your modlist.

**Comment by nthxny** [comment]
nvm, this is a confirmed Accessories bug that should be fixed in the latest release

https://github.com/wisp-forest/accessories/issues/129

**Comment by bonedaddy6969** [comment]
yup i updated accessories mid and it fixed the mob loot drop issue. thanks !
