### ISSUE TITLE
are there any plans for a 1.21 release 

### ISSUE THREAD

**Issue by Omegathenotsofunnyman** [txnimc/ImmersiveLanterns#6]
title says it all, the main reason is  that alot of mods arnt supported for 1.21.1 so i was wondering if you have any plans for a 1.21 release or not

**Comment by nthxny** [comment]
Almost every 1.21.0 mod will work fine on 1.21.1. You can use Fabric dependency overrides if you're on Fabric. Neo might have something else I'm not sure.

You can probably load this on 1.21.0 though, but I don't test on that version.

**Comment by Omegathenotsofunnyman** [comment]
oh alright
