### ISSUE TITLE
issue with lantern possitioning when using a animation resource pack

### ISSUE THREAD

**Issue by ShineIV** [txnimc/ImmersiveLanterns#9]
Hello! theres an issue with lantern positioning when i use this resource pack linked below
https://modrinth.com/resourcepack/just-expressions

the lantern appears on the player's head instead of the place where it should be, i don't if this issue is also happening for other kind of  player animation resource packs.

**Comment by nthxny** [comment]
This should be fixed in the latest versions of Accessories + this mod. If it's still happening you can make another issue
